=== AndriyYavkin/OOP3C/Labs/src/main/resources/Gun.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.firearm.com/schema"
           xmlns:tns="http://www.firearm.com/schema"
           elementFormDefault="qualified">

    <xs:element name="Firearms">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Gun" type="tns:GunType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="GunType">
        <xs:sequence>
            <xs:element name="Model" type="xs:string"/>
            <xs:element name="Handy" type="tns:HandyType"/>
            <xs:element name="Origin" type="xs:string"/>
            <xs:element name="TTCs">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="TTC" type="tns:TTCType" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Material" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="TTCType">
        <xs:sequence>
            <xs:element name="FiringRange" type="tns:FiringRangeType"/>
            <xs:element name="AimRange">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Magazine" type="xs:boolean"/>
            <xs:element name="Optics" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="HandyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ONE_HANDED"/>
            <xs:enumeration value="TWO_HANDED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FiringRangeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CLOSE"/>
            <xs:enumeration value="MEDIUM"/>
            <xs:enumeration value="LONG"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== AndriyYavkin/OOP3C/Labs/target/classes/guns.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Firearms xmlns:tns="http://www.firearm.com/schema"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.firearm.com/schema Gun.xsd">

    <tns:Gun id="g001">
        <tns:Model>AK-47</tns:Model>
        <tns:Handy>TWO_HANDED</tns:Handy>
        <tns:Origin>USSR</tns:Origin>
        <tns:TTCs>
            <tns:TTC>
                <tns:FiringRange>MEDIUM</tns:FiringRange>
                <tns:AimRange>800</tns:AimRange>
                <tns:Magazine>true</tns:Magazine>
                <tns:Optics>false</tns:Optics>
            </tns:TTC>
        </tns:TTCs>
        <tns:Material>Wood/Steel</tns:Material>
    </tns:Gun>

    <tns:Gun id="g002">
        <tns:Model>Desert Eagle</tns:Model>
        <tns:Handy>ONE_HANDED</tns:Handy>
        <tns:Origin>USA/Israel</tns:Origin>
        <tns:TTCs>
            <tns:TTC>
                <tns:FiringRange>CLOSE</tns:FiringRange>
                <tns:AimRange>200</tns:AimRange>
                <tns:Magazine>true</tns:Magazine>
                <tns:Optics>false</tns:Optics>
            </tns:TTC>
        </tns:TTCs>
        <tns:Material>Steel</tns:Material>
    </tns:Gun>

</tns:Firearms>

=== AndriyYavkin/OOP3C/Labs/guns_new_output.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Firearms xmlns="http://www.firearm.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firearm.com/schema Gun.xsd">
    <Gun id="g001">
        <Model>AK-47</Model>
        <Handy>TWO_HANDED</Handy>
        <Origin>USSR</Origin>
        <TTCs>
            <TTC>
                <FiringRange>MEDIUM</FiringRange>
                <AimRange>800</AimRange>
                <Magazine>true</Magazine>
                <Optics>false</Optics>
            </TTC>
        </TTCs>
        <Material>Wood/Steel</Material>
    </Gun>
    <Gun id="g002">
        <Model>Desert Eagle</Model>
        <Handy>ONE_HANDED</Handy>
        <Origin>USA/Israel</Origin>
        <TTCs>
            <TTC>
                <FiringRange>CLOSE</FiringRange>
                <AimRange>200</AimRange>
                <Magazine>true</Magazine>
                <Optics>false</Optics>
            </TTC>
        </TTCs>
        <Material>Steel</Material>
    </Gun>
    <Gun id="g005">
        <Model>FN SCAR</Model>
        <Handy>TWO_HANDED</Handy>
        <Origin>Belgium</Origin>
        <TTCs>
            <TTC>
                <FiringRange>MEDIUM</FiringRange>
                <AimRange>600</AimRange>
                <Magazine>true</Magazine>
                <Optics>true</Optics>
            </TTC>
        </TTCs>
        <Material>Polymer/Aluminum</Material>
    </Gun>
    <Gun id="g004">
        <Model>Glock 19</Model>
        <Handy>ONE_HANDED</Handy>
        <Origin>Austria</Origin>
        <TTCs>
            <TTC>
                <FiringRange>CLOSE</FiringRange>
                <AimRange>50</AimRange>
                <Magazine>true</Magazine>
                <Optics>false</Optics>
            </TTC>
        </TTCs>
        <Material>Polymer</Material>
    </Gun>
    <Gun id="g003">
        <Model>M16</Model>
        <Handy>TWO_HANDED</Handy>
        <Origin>USA</Origin>
        <TTCs>
            <TTC>
                <FiringRange>MEDIUM</FiringRange>
                <AimRange>550</AimRange>
                <Magazine>true</Magazine>
                <Optics>false</Optics>
            </TTC>
        </TTCs>
        <Material>Polymer/Steel</Material>
    </Gun>
    <Gun id="g006">
        <Model>Beretta 92</Model>
        <Handy>ONE_HANDED</Handy>
        <Origin>Italy</Origin>
        <TTCs>
            <TTC>
                <FiringRange>CLOSE</FiringRange>
                <AimRange>50</AimRange>
                <Magazine>true</Magazine>
                <Optics>false</Optics>
            </TTC>
        </TTCs>
        <Material>Aluminum/Steel</Material>
    </Gun>
</Firearms>
